[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#282c34"
blue = "#7cb7ff"
cyan = "#00c1e4"
green = "#cae7b9"
magenta = "#d7bcc8"
red = "#f67e7d"
white = "#00c1e4"
yellow = "#e1dd8f"

[colors.primary]
background = "#0D1326"
foreground = "#c3c7d1"

[font]
size = 11.0

[font.bold]
family = "Monaspace Argon Var"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon Var"
style = "Bold Italic"

[font.italic]
family = "Monaspace Argon Var"
style = "Semibold Italic"

[font.normal]
family = "Monaspace Argon Var"
style = "Semibold"

[scrolling]
history = 50000

[window]
opacity = 0.9
